# -*- coding: utf-8 -*-
"""Map 1 - World

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HxYBHA31Gc5ljv6gF80-_vG6UhugN64_
"""

pip install geopandas

import geopandas as gpd
import matplotlib.pyplot as plt

url = "https://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_0_countries.zip"
world = gpd.read_file(url)
world.plot()
plt.show()

